name: Pathtracer Build

on:
  push:
    branches:
    - master
    paths:
    - 'pathtracer/**'
    - 'external/**'
    
  pull_request:
    branches:
    - master
    paths:
    - 'pathtracer/**'
    - 'external/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cd pathtracer && mkdir bin && cd bin && cmake ..
    - name: build
      run: cd pathtracer/bin && make
    - name: test
      run: cd pathtracer && bin/pathtracer -t

  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.0.3
    - name: configure
      run: cd pathtracer && mkdir bin && cd bin && cmake .. -G "Visual Studio 14 2015 Win64"
    - name: build
      run: MSBuild.exe pathtracer\bin\PathTracer.sln /p:Configuration=Release
    - name: test
      run: cd pathtracer && bin\Release\pathtracer -t
